
export interface Professional {
  id: string
  name: string
  image: string
  region: string
  specialisms: string[]
  bio: string
  experienceLevel: string
  languages: string[]
  verified: boolean
  rateInfo: string
  linkedinUrl: string
  lastVerified: string
  supportOptions: string[]
}

export const mockProfessionals: Professional[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    image: "/placeholder.svg?height=200&width=200&text=Sarah+Johnson",
    region: "London",
    specialisms: ["Child Arrangements", "Financial Disputes", "Domestic Violence"],
    bio: "Experienced McKenzie Friend with over 8 years supporting families through court proceedings. Specializes in child arrangement orders and financial disputes.",
    experienceLevel: "Senior",
    languages: ["English", "French"],
    verified: true,
    rateInfo: "£50-80 per hour",
    linkedinUrl: "",
    lastVerified: "2024-01-15",
    supportOptions: ["Court Accompaniment", "Document Preparation", "Case Strategy"],
  },
  {
    id: "2",
    name: "Michael Chen",
    image: "/placeholder.svg?height=200&width=200&text=Michael+Chen",
    region: "Manchester",
    specialisms: ["Property Disputes", "Child Support", "Mediation"],
    bio: "Qualified mediator and McKenzie Friend helping families resolve disputes outside of court when possible. Strong background in property and financial matters.",
    experienceLevel: "Intermediate",
    languages: ["English", "Mandarin"],
    verified: true,
    rateInfo: "£40-60 per hour",
    linkedinUrl: "",
    lastVerified: "2024-01-10",
    supportOptions: ["Mediation Support", "Document Review", "Court Preparation"],
  },
  {
    id: "3",
    name: "Emma Williams",
    image: "/placeholder.svg?height=200&width=200&text=Emma+Williams",
    region: "Birmingham",
    specialisms: ["Domestic Violence", "Emergency Applications", "Child Protection"],
    bio: "Former social worker now providing McKenzie Friend services. Specializes in urgent applications and domestic violence cases with a compassionate approach.",
    experienceLevel: "Senior",
    languages: ["English", "Welsh"],
    verified: true,
    rateInfo: "£45-70 per hour",
    linkedinUrl: "",
    lastVerified: "2024-01-20",
    supportOptions: ["Emergency Support", "Safety Planning", "Court Accompaniment"],
  },
  {
    id: "4",
    name: "David Thompson",
    image: "/placeholder.svg?height=200&width=200&text=David+Thompson",
    region: "Leeds",
    specialisms: ["Financial Orders", "Property Division", "Pension Sharing"],
    bio: "Former financial advisor specializing in complex financial arrangements in family court. Helps clients understand financial settlements and pension sharing orders.",
    experienceLevel: "Senior",
    languages: ["English"],
    verified: true,
    rateInfo: "£60-90 per hour",
    linkedinUrl: "",
    lastVerified: "2024-01-12",
    supportOptions: ["Financial Analysis", "Document Preparation", "Court Support"],
  },
  {
    id: "5",
    name: "Lisa Rodriguez",
    image: "/placeholder.svg?height=200&width=200&text=Lisa+Rodriguez",
    region: "Bristol",
    specialisms: ["Child Custody", "International Family Law", "Relocation Cases"],
    bio: "Bilingual McKenzie Friend with expertise in complex international family law matters. Helps families navigate cross-border custody disputes.",
    experienceLevel: "Intermediate",
    languages: ["English", "Spanish"],
    verified: true,
    rateInfo: "£45-65 per hour",
    linkedinUrl: "",
    lastVerified: "2024-01-18",
    supportOptions: ["Translation Services", "International Documentation", "Court Support"],
  },
  {
    id: "6",
    name: "James Mitchell",
    image: "/placeholder.svg?height=200&width=200&text=James+Mitchell",
    region: "Edinburgh",
    specialisms: ["Scottish Family Law", "Cohabitation Rights", "Civil Partnerships"],
    bio: "Specialist in Scottish family law with particular expertise in cohabitation rights and civil partnership matters. Former paralegal with 10 years experience.",
    experienceLevel: "Senior",
    languages: ["English", "Gaelic"],
    verified: true,
    rateInfo: "£55-85 per hour",
    linkedinUrl: "",
    lastVerified: "2024-01-14",
    supportOptions: ["Scottish Law Expertise", "Document Drafting", "Court Representation"],
  },
  {
    id: "7",
    name: "Rachel Thompson",
    image: "/placeholder.svg?height=200&width=200&text=Rachel+Thompson",
    region: "Cardiff",
    specialisms: ["Care Proceedings", "Child Protection", "Family Court"],
    bio: "Former family court clerk with extensive knowledge of care proceedings and child protection cases. Provides compassionate support to families navigating complex court systems.",
    experienceLevel: "Senior",
    languages: ["English", "Welsh"],
    verified: true,
    rateInfo: "£50-75 per hour",
    linkedinUrl: "",
    lastVerified: "2024-01-16",
    supportOptions: ["Care Proceedings Support", "Document Assistance", "Court Navigation"],
  },
  {
    id: "8",
    name: "Ahmed Hassan",
    image: "/placeholder.svg?height=200&width=200&text=Ahmed+Hassan",
    region: "Birmingham",
    specialisms: ["Immigration Family Law", "Forced Marriage", "Cultural Mediation"],
    bio: "Specialist in culturally sensitive family law matters with particular expertise in forced marriage cases and immigration-related family disputes.",
    experienceLevel: "Intermediate",
    languages: ["English", "Arabic", "Urdu"],
    verified: true,
    rateInfo: "£40-65 per hour",
    linkedinUrl: "",
    lastVerified: "2024-01-11",
    supportOptions: ["Cultural Mediation", "Translation Services", "Family Advocacy"],
  },
  {
    id: "9",
    name: "Sophie Anderson",
    image: "/placeholder.svg?height=200&width=200&text=Sophie+Anderson",
    region: "Newcastle",
    specialisms: ["Adoption", "Surrogacy", "Parental Rights"],
    bio: "Former adoption social worker now helping families with adoption proceedings, surrogacy agreements, and establishing parental rights through the court system.",
    experienceLevel: "Senior",
    languages: ["English"],
    verified: true,
    rateInfo: "£55-80 per hour",
    linkedinUrl: "",
    lastVerified: "2024-01-13",
    supportOptions: ["Adoption Support", "Legal Documentation", "Court Preparation"],
  },
  {
    id: "10",
    name: "Connor Murphy",
    image: "/placeholder.svg?height=200&width=200&text=Connor+Murphy",
    region: "Belfast",
    specialisms: ["Northern Ireland Family Law", "Custody Disputes", "Maintenance Orders"],
    bio: "Experienced in Northern Ireland family law with particular focus on custody disputes and maintenance order enforcement. Former court administrative officer.",
    experienceLevel: "Intermediate",
    languages: ["English", "Irish"],
    verified: false,
    rateInfo: "£35-55 per hour",
    linkedinUrl: "",
    lastVerified: "2024-01-08",
    supportOptions: ["Northern Ireland Law", "Court Documentation", "Maintenance Support"],
  },
  {
    id: "11",
    name: "Priya Patel",
    image: "/placeholder.svg?height=200&width=200&text=Priya+Patel",
    region: "Leicester",
    specialisms: ["Cross-Cultural Disputes", "Religious Divorce", "Family Mediation"],
    bio: "Multilingual mediator specializing in cross-cultural family disputes and religious divorce proceedings. Background in community advocacy and family support services.",
    experienceLevel: "Intermediate",
    languages: ["English", "Hindi", "Gujarati"],
    verified: true,
    rateInfo: "£45-70 per hour",
    linkedinUrl: "",
    lastVerified: "2024-01-17",
    supportOptions: ["Cultural Mediation", "Religious Law Guidance", "Family Counseling"],
  },
  {
    id: "12",
    name: "Thomas Wright",
    image: "/placeholder.svg?height=200&width=200&text=Thomas+Wright",
    region: "Liverpool",
    specialisms: ["Mental Health Court", "Capacity Issues", "Vulnerable Adults"],
    bio: "Former mental health advocate with expertise in court of protection matters, capacity assessments, and supporting vulnerable adults through family court proceedings.",
    experienceLevel: "Senior",
    languages: ["English"],
    verified: true,
    rateInfo: "£50-85 per hour",
    linkedinUrl: "",
    lastVerified: "2024-01-19",
    supportOptions: ["Mental Health Advocacy", "Capacity Assessments", "Vulnerable Adult Support"],
  }
]
