export interface Professional {
  id: string
  "Name": string
  "Profile Photo": string
  "Region": string
  "Specialisms": string[]
  "Short Bio": string
  "Experience Level": string
  "Languages Spoken": string[]
  "Verified": boolean
  "Rate Info": string
  "LinkedIn Profile Link": string
  "Last Verified Date": string
}

export const mockProfessionals: Professional[] = [
  {
    id: "1",
    "Name": "Sarah Johnson",
    "Profile Photo": "/placeholder.svg?height=200&width=200&text=Sarah+Johnson",
    "Region": "London",
    "Specialisms": ["Child arrangements", "Divorce support", "Court preparation"],
    "Short Bio": "Experienced McKenzie Friend with over 10 years helping families navigate complex legal situations. Specializing in child custody and divorce proceedings.",
    "Experience Level": "5+ years",
    "Languages Spoken": ["English", "Spanish"],
    "Verified": true,
    "Rate Info": "£45-60 per hour",
    "LinkedIn Profile Link": "",
    "Last Verified Date": "2024-01-15",
  },
  {
    id: "2",
    "Name": "Michael Chen",
    "Profile Photo": "/placeholder.svg?height=200&width=200&text=Michael+Chen",
    "Region": "North West",
    "Specialisms": ["Language support", "Multicultural family cases", "Court preparation"],
    "Short Bio": "Former HR professional turned McKenzie Friend, dedicated to helping individuals understand their workplace rights and navigate employment disputes.",
    "Experience Level": "1–3 years",
    "Languages Spoken": ["English", "Mandarin"],
    "Verified": true,
    "Rate Info": "£40-55 per hour",
    "LinkedIn Profile Link": "",
    "Last Verified Date": "2024-01-10",
  },
  {
    id: "3",
    "Name": "Emma Williams",
    "Profile Photo": "/placeholder.svg?height=200&width=200&text=Emma+Williams",
    "Region": "Midlands",
    "Specialisms": ["Child arrangements", "Emotional guidance", "Court preparation"],
    "Short Bio": "Community advocate with extensive experience in housing law, helping tenants understand their rights and defend against unfair evictions.",
    "Experience Level": "5+ years",
    "Languages Spoken": ["English"],
    "Verified": true,
    "Rate Info": "£50-70 per hour",
    "LinkedIn Profile Link": "",
    "Last Verified Date": "2024-01-12",
  },
  {
    id: "4",
    "Name": "David Thompson",
    "Profile Photo": "/placeholder.svg?height=200&width=200&text=David+Thompson",
    "Region": "North East",
    "Specialisms": ["Divorce support", "Emotional guidance"],
    "Short Bio": "Financial advisor turned McKenzie Friend, specializing in debt management and helping individuals navigate bankruptcy proceedings.",
    "Experience Level": "0–1 years",
    "Languages Spoken": ["English"],
    "Verified": false,
    "Rate Info": "£30-45 per hour",
    "LinkedIn Profile Link": "",
    "Last Verified Date": "2024-01-08",
  },
  {
    id: "5",
    "Name": "Lisa Rodriguez",
    "Profile Photo": "/placeholder.svg?height=200&width=200&text=Lisa+Rodriguez",
    "Region": "London",
    "Specialisms": ["Multicultural family cases", "Language support", "Child arrangements"],
    "Short Bio": "Multilingual McKenzie Friend with deep understanding of immigration law, helping families reunite and individuals seek asylum.",
    "Experience Level": "5+ years",
    "Languages Spoken": ["English", "Spanish", "Portuguese"],
    "Verified": true,
    "Rate Info": "£55-75 per hour",
    "LinkedIn Profile Link": "",
    "Last Verified Date": "2024-01-18",
  },
  {
    id: "6",
    "Name": "James MacLeod",
    "Profile Photo": "/placeholder.svg?height=200&width=200&text=James+MacLeod",
    "Region": "Scotland",
    "Specialisms": ["Child arrangements", "SEN/Disability cases", "Court preparation"],
    "Short Bio": "Scottish law specialist with over 15 years of experience in family court proceedings. Expert in Scottish legal system and child welfare cases.",
    "Experience Level": "5+ years",
    "Languages Spoken": ["English", "Scottish Gaelic"],
    "Verified": true,
    "Rate Info": "£60-85 per hour",
    "LinkedIn Profile Link": "",
    "Last Verified Date": "2024-01-14",
  },
  {
    id: "7",
    "Name": "Rachel Thompson",
    "Profile Photo": "/placeholder.svg?height=200&width=200&text=Rachel+Thompson",
    "Region": "South East",
    "Specialisms": ["Child arrangements", "SEN/Disability cases", "Court preparation"],
    "Short Bio": "Former family court clerk with extensive knowledge of care proceedings and child protection cases. Provides compassionate support to families navigating complex court systems.",
    "Experience Level": "5+ years",
    "Languages Spoken": ["English", "Welsh"],
    "Verified": true,
    "Rate Info": "£50-75 per hour",
    "LinkedIn Profile Link": "",
    "Last Verified Date": "2024-01-16",
  },
  {
    id: "8",
    "Name": "Ahmed Hassan",
    "Profile Photo": "/placeholder.svg?height=200&width=200&text=Ahmed+Hassan",
    "Region": "Midlands",
    "Specialisms": ["Multicultural family cases", "Language support"],
    "Short Bio": "Specialist in culturally sensitive family law matters with particular expertise in forced marriage cases and immigration-related family disputes.",
    "Experience Level": "1–3 years",
    "Languages Spoken": ["English", "Arabic", "Urdu"],
    "Verified": true,
    "Rate Info": "£40-65 per hour",
    "LinkedIn Profile Link": "",
    "Last Verified Date": "2024-01-11",
  },
  {
    id: "9",
    "Name": "Sophie Anderson",
    "Profile Photo": "/placeholder.svg?height=200&width=200&text=Sophie+Anderson",
    "Region": "North East",
    "Specialisms": ["Child arrangements", "Emotional guidance", "SEN/Disability cases"],
    "Short Bio": "Former adoption social worker now helping families with adoption proceedings, surrogacy agreements, and establishing parental rights through the court system.",
    "Experience Level": "5+ years",
    "Languages Spoken": ["English"],
    "Verified": true,
    "Rate Info": "£55-80 per hour",
    "LinkedIn Profile Link": "",
    "Last Verified Date": "2024-01-13",
  },
  {
    id: "10",
    "Name": "Connor Murphy",
    "Profile Photo": "/placeholder.svg?height=200&width=200&text=Connor+Murphy",
    "Region": "South East",
    "Specialisms": ["Child arrangements", "Divorce support"],
    "Short Bio": "Experienced in Northern Ireland family law with particular focus on custody disputes and maintenance order enforcement. Former court administrative officer.",
    "Experience Level": "1–3 years",
    "Languages Spoken": ["English", "Irish"],
    "Verified": false,
    "Rate Info": "£35-55 per hour",
    "LinkedIn Profile Link": "",
    "Last Verified Date": "2024-01-08",
  },
  {
    id: "11",
    "Name": "Priya Patel",
    "Profile Photo": "/placeholder.svg?height=200&width=200&text=Priya+Patel",
    "Region": "Midlands",
    "Specialisms": ["Multicultural family cases", "Divorce support", "Language support"],
    "Short Bio": "Multilingual mediator specializing in cross-cultural family disputes and religious divorce proceedings. Background in community advocacy and family support services.",
    "Experience Level": "1–3 years",
    "Languages Spoken": ["English", "Hindi", "Gujarati"],
    "Verified": true,
    "Rate Info": "£45-70 per hour",
    "LinkedIn Profile Link": "",
    "Last Verified Date": "2024-01-17",
  },
  {
    id: "12",
    "Name": "Thomas Wright",
    "Profile Photo": "/placeholder.svg?height=200&width=200&text=Thomas+Wright",
    "Region": "South West",
    "Specialisms": ["SEN/Disability cases", "Emotional guidance", "Court preparation"],
    "Short Bio": "Former mental health advocate with expertise in court of protection matters, capacity assessments, and supporting vulnerable adults through family court proceedings.",
    "Experience Level": "5+ years",
    "Languages Spoken": ["English"],
    "Verified": true,
    "Rate Info": "£50-85 per hour",
    "LinkedIn Profile Link": "",
    "Last Verified Date": "2024-01-19",
  }
]